name: Deploy
on:
  push:
    branches: ['main']

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: cd /srv/cards && eval "$(ssh-agent -s)" && ssh-add && git pull origin main && npm ci && pm2 reload ecosystem.config.js && pm2 startup